### ISSUE TITLE
Plugin not working with Joomla 5.0.0.

### ISSUE THREAD

**Issue by roberb7** [SharkyKZ/joomla-recaptcha-v3-plugin#1]
When using a Joomla contact form, the "protected by Joomla" graphic appears in the lower right corner, but the "Send Email" button does nothing. The borwser console shows: 
Uncaught TypeError: action.replace is not a function
    <anonymous> http://broughton.ca/media/plg_captcha_recaptcha_v3/js/main.js?0aff1f8e:28
[main.js:28:36](http://broughton.ca/media/plg_captcha_recaptcha_v3/js/main.js?0aff1f8e)
    <anonymous> http://broughton.ca/media/plg_captcha_recaptcha_v3/js/main.js?0aff1f8e:28

**Comment by roberb7** [comment]
On 15/11/23 04:43, SharkyKZ wrote:
>
> Fixed in 616be8d 
> <https://github.com/SharkyKZ/joomla-recaptcha-v3-plugin/commit/616be8d5772471c32668fb48352d6aa25236caec>.
>
Seems to be working OK. Go to https://broughton.ca/contact to see it in 
action.

**Comment by SharkyKZ** [comment]
SP Page Builder Pro does not support this or any 3rd party captcha plugin. It has hardcoded support for the two Joomla core plugins (reCAPTCHA and Invisible reCAPTCHA) both of which have been removed from Joomla 5.0.
